title: "Samuel Baguma — AI Security Blog"
description: "Deep dives on AI security, model protection, and adversarial defense."
theme: minima
author: Samuel Baguma
email: samuel.baguma@example.com
github_username: bagumas
linkedin: https://www.linkedin.com/in/samuel-baguma-37a45110/

show_excerpts: true
future: true

minima:
  skin: dark
  social_links:
    - platform: github
      user_url: https://github.com/bagumas
    - platform: linkedin
      user_url: https://www.linkedin.com/in/samuel-baguma-37a45110/

plugins:
  - jekyll-feed

